name: Build Artifacts

on: [push]

jobs:
  build-linux-artifact:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - uses: actions/upload-artifact@v4
      with:
        name: protobufjson-linux-${{ github.sha }}.tar.gz
        path: |
          JsonToProto
          ProtoToJson
        if-no-files-found: error

  build-osx-intel-artifact:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - uses: actions/upload-artifact@v4
      with:
        name: protobufjson-macos-intel-${{ github.sha }}.tar.gz
        path: |
          JsonToProto
          ProtoToJson
        if-no-files-found: error

  build-osx-arm-artifact:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - uses: actions/upload-artifact@v4
      with:
        name: protobufjson-macos-arm-${{ github.sha }}.tar.gz
        path: |
          JsonToProto
          ProtoToJson
        if-no-files-found: error
